# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 6.790 <br> Machine Learning
tagline: 6.790 Machine Learning, Fall 2025
email: 6.790-website@mit.edu
description: "Graduate Machine Learning Course, MIT EECS, Fall 2025."
# logo: "/assets/images/790-txt.png"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gradml.mit.edu" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# remote_theme: "just-the-docs"
# theme: "just-the-docs"
heading_anchors: true
permalink: pretty
aux_links:
  Canvas:
    - "https://canvas.mit.edu/courses/33927"
  Piazza:
    - "https://piazza.com/mit/fall2025/67900"
aux_links_new_tab: true

#remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-default-layout
  # - jekyll-pandoc
  - jekyll-last-modified-at
  - jekyll-seo-tag

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
nav_next_prev: true

last_edit_timestamp: true
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "✏️ Edit this page on GitHub"
gh_edit_repository: "https://github.com/790gradml/gradML"
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree"

# Sidebar external links (rendered as tabs/links in the nav)
nav_external_links:
  - title: Home
    url: "/"
    hide_icon: true

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
  date-format: "%d-%b-%Y"
# kramdown:
# math_engine: katex
# input: GFMKatex # GFMKatex class from sp301415 is in _plugins/server-side-math.rb
# math_engine_opts:
#     katex_js: "assets/js/katex.min.js"
#     debug: true
#     verbose: true
#     js_run: Node
#     katex_opts:
#         throwOnError: false
#         macros: {} # lots of macros here
# math: mathjax
# math: katex
# markdown: Pandoc
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
color_scheme: wider
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - venv/
  - gradML_sources
  - booksNotes/
# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
  homeworks:
  lectures:
  projects:

  # Define a collection named "resource", its documents reside in the "_resource" directory
  # resource:
  #permalink: "/:collection/:path/"
  # permalink: "/:path/"
  # output: true
# Default layouts for each collection type
defaults:
  - scope:
      path: ""
      type: staffers
    values:
      layout: staffer
      subpath: "/assets/images/staffers/"
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement
  - scope:
      path: "supervised/"
    values:
      parent: Supervised Learning
      layout: page
      katex: true
  - scope:
      path: "reinforcement/"
    values:
      parent: Reinforcement Learning
      layout: page
  - scope:
      path: "unsupervised/"
    values:
      parent: Unsupervised Learning
      layout: page
  - scope:
      path: "info/"
    values:
      layout: page
      info_cat: true
  - scope:
      path: "homeworks/"
    values:
      layout: page
      permalink: homeworks/:basename/
# pandoc:
#     extensions:
#         # - normalize
#         # - csl: _styles/apa.csl
#         - bibliography: _bib/*.bibs

# callouts
callouts_level: quiet # or loud
callouts:
  definition:
    title: Definition
    color: yellow
  theorem:
    title: Theorem
    color: eecs-red
  proof:
    title: Proof
    color: eecs-blue
  note:
    title: Note
    color: blue
  warning:
    title: ""
    color: eecs-red
  alt-warning:
    title: ""
    color: yellow
  example:
    title: "Example"
    color: eecs-purple
  exercise:
    title: "Exercise"
    color: blue
  solutions:
    title: "Solutions"
    color: mit-gray
# mermaid:
#     # Version of mermaid library
#     # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
#     version: "9.1.7"
